apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
type: Opaque
stringData:
  azurestorageaccountname: ipmdsa
  azurestorageaccountkey: oR0+hRsvUBPhF83BYcKhyLdYAaYCKk5MvVxROcyUa5vvw9g0X0ykTfS04R/E2m2LIF+0NNLAZ/qX+ASttASwRA==